# Generated by Django 5.2.5 on 2025-09-15 14:58

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('idCat', models.AutoField(primary_key=True, serialize=False)),
                ('nomCat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rayon',
            fields=[
                ('idRayon', models.AutoField(primary_key=True, serialize=False)),
                ('nomRayon', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('idStatus', models.AutoField(primary_key=True, serialize=False)),
                ('libelleStatus', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('refProd', models.AutoField(primary_key=True, serialize=False)),
                ('intituleProd', models.CharField(max_length=200)),
                ('prixUnitaireProd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dateFabProd', models.DateField(default=datetime.date.today)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits_categorie', to='monApp.categorie')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits_status', to='monApp.statut')),
            ],
        ),
        migrations.CreateModel(
            name='Contenir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qte', models.PositiveIntegerField()),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenir_produit', to='monApp.produit')),
                ('rayon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenir_rayon', to='monApp.rayon')),
            ],
            options={
                'unique_together': {('produit', 'rayon')},
            },
        ),
    ]
