# Generated by Django 5.2.5 on 2025-09-08 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0002_rayon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.IntegerField()),
                ('idRayon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contient', to='monApp.rayon')),
                ('refProd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contient', to='monApp.produit')),
            ],
        ),
    ]
