# Generated by Django 5.2.5 on 2025-09-08 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0003_contenir'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='date_fab',
            field=models.DateField(default=datetime.datetime(2025, 9, 8, 14, 57, 2, 82635, tzinfo=datetime.timezone.utc)),
        ),
    ]
