# Generated by Django 5.2.5 on 2025-09-15 13:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0004_produit_date_fab'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('idStatut', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='produit',
            name='date_fab',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
