# Generated by Django 5.2.5 on 2025-09-15 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0005_statut_alter_produit_date_fab'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='statut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='monApp.statut'),
        ),
    ]
